Implement bi-directional RPC streaming
loopholelabs/frisbee-go pull request #128
Opened 2022-06-01 17:25 UTC by SuperManifolds

## Description

Implements support for stream methods from proto files in FRPC.
This change modifies the properties encoded into request and response objects and so needs to be deployed to both client and server.

Fixes #123 

## Type of change

**Please update the title of this PR to reflect the type of change.** (Delete the ones that aren't required).

- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Final Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules
- [ x] I have checked my code and corrected any misspellings

2022-06-01 18:54 UTC, ShivanshVij reviewed
Overall it looks good but it's really hard to grok what's actually going on until we actually try it.

Can you attach a generated code sample to this PR?

2022-06-01 18:54 UTC, ShivanshVij commented on protoc-gen-frpc/templates/structs.templ
> +        streamID uint32
We should only generate the streamID field if we are doing streaming - otherwise we shouldn't generate it at all.

2022-06-01 18:54 UTC, ShivanshVij commented on protoc-gen-frpc/templates/structs.templ
> +        streamID uint32
Same with the status field since I can't imagine it being used in non-streaming examples

2022-06-08 22:29 UTC, SuperManifolds commented
New generated bidirectional streaming example

```go
// Code generated by FRPC v0.1.0, DO NOT EDIT.
// source: protoc-gen-frpc/examples/hack/hack.proto

package hack

import (
	"github.com/loopholelabs/frisbee/pkg/packet"
	"errors"
	"io"

	"github.com/loopholelabs/frisbee"
	"github.com/rs/zerolog"
	"crypto/tls"
	"context"

	"sync"
	"github.com/loopholelabs/frisbee/internal/queue"
)

var streamIdLength = 24
var statusLength = 8
var streamStatusMask uint32 = 0xFF000000

var (
	NilDecode = errors.New("cannot decode into a nil root struct")
)

type Request struct {
	error error
	flags uint8

	Message int32
}

func NewRequest() *Request {
	return &Request{}
}

func (x *Request) Error(p *packet.Packet, err error) {
	packet.Encoder(p).Error(err)
}

func (x *Request) Encode(p *packet.Packet) {
	if x == nil {
		packet.Encoder(p).Nil()
	} else if x.error != nil {
		packet.Encoder(p).Error(x.error)
	} else {
		packet.Encoder(p).Uint8(x.flags).Int32(x.Message)
	}
}

func (x *Request) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := packet.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Request) decode(d *packet.Decoder) error {
	if d.Nil() {
		return nil
	}
	var err error
	var flags uint8

	x.error, err = d.Error()
	if err != nil {
		flags, err = d.Uint8()
		if err != nil {
			return err
		}
		x.flags = flags

		x.Message, err = d.Int32()
		if err != nil {
			return err
		}
	}
	return nil
}

type Response struct {
	error error
	flags uint8

	Message int32
}

func NewResponse() *Response {
	return &Response{}
}

func (x *Response) Error(p *packet.Packet, err error) {
	packet.Encoder(p).Error(err)
}

func (x *Response) Encode(p *packet.Packet) {
	if x == nil {
		packet.Encoder(p).Nil()
	} else if x.error != nil {
		packet.Encoder(p).Error(x.error)
	} else {
		packet.Encoder(p).Uint8(x.flags).Int32(x.Message)
	}
}

func (x *Response) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := packet.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Response) decode(d *packet.Decoder) error {
	if d.Nil() {
		return nil
	}
	var err error
	var flags uint8

	x.error, err = d.Error()
	if err != nil {
		flags, err = d.Uint8()
		if err != nil {
			return err
		}
		x.flags = flags

		x.Message, err = d.Int32()
		if err != nil {
			return err
		}
	}
	return nil
}

type EchoService interface {
	Echo(context.Context, *Request) (*Response, error)

	EchoStream(srv EchoStreamServer) error
}

type Server struct {
	*frisbee.Server

	nextEchoStream       uint16
	nextEchoStreamMu     sync.RWMutex
	inflightEchoStreamMu sync.RWMutex
	inflightEchoStream   map[uint16]*queue.Circular[Request, *Request]
}

func NewServer(echoService EchoService, tlsConfig *tls.Config, logger *zerolog.Logger) (*Server, error) {
	var s *Server
	table := make(frisbee.HandlerTable)

	table[10] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		req := NewRequest()
		err := req.Decode(incoming.Content.B)
		if err == nil {
			var res *Response
			outgoing = incoming
			outgoing.Content.Reset()
			res, err = echoService.Echo(ctx, req)
			if err != nil {
				res.Error(outgoing, err)
			} else {
				res.Encode(outgoing)
			}
			outgoing.Metadata.ContentLength = uint32(len(outgoing.Content.B))
		}
		return
	}
	table[11] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		req := NewRequest()
		err := req.Decode(incoming.Content.B)
		if err == nil {
			s.inflightEchoStreamMu.Lock()
			if q, ok := s.inflightEchoStream[incoming.Metadata.Id]; ok {
				q.Push(req)
				s.inflightEchoStreamMu.Unlock()
			} else {
				q := queue.NewCircular[Request, *Request](100)
				s.inflightEchoStream[incoming.Metadata.Id] = q
				q.Push(req)
				s.inflightEchoStreamMu.Unlock()
				id := incoming.Metadata.Id
				conn := ctx.Value("conn").(*frisbee.Async)
				recv := func() (*Request, error) {
					p, err := q.Pop()
					if p.flags == 1 {
						return nil, io.EOF
					}
					return p, err
				}

				send := func(m *Response) error {
					p := packet.Get()
					p.Metadata.Operation = 11

					p.Metadata.Id = id

					m.Encode(p)
					p.Metadata.ContentLength = uint32(len(p.Content.B))
					err := conn.WritePacket(p)
					if err != nil {
						packet.Put(p)
						return err
					}
					packet.Put(p)
					return nil
				}
				srv := EchoStreamServer{
					context: ctx,
					recv:    recv, send: send}
				go func() {
					err := echoService.EchoStream(srv)
					if err != nil {
						res := Response{error: err}
						srv.Send(&res)
					}
					s.inflightEchoStreamMu.Lock()
					s.inflightEchoStream[incoming.Metadata.Id] = nil
					s.inflightEchoStreamMu.Unlock()
				}()

			}
		}
		return
	}
	var fsrv *frisbee.Server
	var err error
	if tlsConfig != nil {
		fsrv, err = frisbee.NewServer(table, frisbee.WithTLS(tlsConfig), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	} else {
		fsrv, err = frisbee.NewServer(table, frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	}

	fsrv.ConnContext = func(ctx context.Context, conn *frisbee.Async) context.Context {
		return context.WithValue(ctx, "conn", conn)
	}
	s, err = &Server{
		Server: fsrv,
	}, nil

	s.nextEchoStream = 0
	s.inflightEchoStream = make(map[uint16]*queue.Circular[Request, *Request])
	return s, err
}

type EchoStreamServer struct {
	context context.Context
	recv    func() (*Request, error)
	send    func(*Response) error
}

func (x *EchoStreamServer) Context() context.Context {
	return x.context
}

func (x *EchoStreamServer) Recv() (*Request, error) {
	return x.recv()
}

func (x *EchoStreamServer) Send(m *Response) error {
	return x.send(m)
}

type Client struct {
	*frisbee.Client
	nextEcho             uint16
	nextEchoMu           sync.RWMutex
	inflightEchoMu       sync.RWMutex
	inflightEcho         map[uint16]chan *Response
	nextEchoStream       uint16
	nextEchoStreamMu     sync.RWMutex
	inflightEchoStreamMu sync.RWMutex

	inflightEchoStream map[uint16]*queue.Circular[Response, *Response]
}

func NewClient(tlsConfig *tls.Config, logger *zerolog.Logger) (*Client, error) {
	c := new(Client)
	table := make(frisbee.HandlerTable)

	table[10] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		c.inflightEchoMu.RLock()
		if ch, ok := c.inflightEcho[incoming.Metadata.Id]; ok {
			c.inflightEchoMu.RUnlock()
			res := NewResponse()
			res.Decode(incoming.Content.B)
			ch <- res
		} else {
			c.inflightEchoMu.RUnlock()
		}
		return
	}
	table[11] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		c.inflightEchoStreamMu.RLock()
		res := NewResponse()
		err := res.Decode(incoming.Content.B)
		if err == nil {
			if q, ok := c.inflightEchoStream[incoming.Metadata.Id]; ok {
				err := q.Push(res)
				if err != nil {
					c.inflightEchoStreamMu.RUnlock()
					return nil, 0
				}
			}
		}
		c.inflightEchoStreamMu.RUnlock()
		return
	}
	var err error
	if tlsConfig != nil {
		c.Client, err = frisbee.NewClient(table, context.Background(), frisbee.WithTLS(tlsConfig), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	} else {
		c.Client, err = frisbee.NewClient(table, context.Background(), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	}

	c.nextEcho = 0
	c.inflightEcho = make(map[uint16]chan *Response)
	c.nextEchoStream = 0
	c.inflightEchoStream = make(map[uint16]*queue.Circular[Response, *Response])
	return c, nil
}

func (c *Client) Echo(ctx context.Context, req *Request) (res *Response, err error) {
	ch := make(chan *Response, 1)
	p := packet.Get()
	p.Metadata.Operation = 10

	c.nextEchoMu.Lock()
	c.nextEcho += 1
	p.Metadata.Id = c.nextEcho
	c.nextEchoMu.Unlock()

	req.Encode(p)
	p.Metadata.ContentLength = uint32(len(p.Content.B))
	c.inflightEchoMu.Lock()
	c.inflightEcho[p.Metadata.Id] = ch
	c.inflightEchoMu.Unlock()
	err = c.Client.WritePacket(p)
	if err [...]

2022-06-09 16:04 UTC, SuperManifolds commented
Yeah that was a silly oversight on my part, I'll change it to always handle the flags and sort out the other issues

2022-06-09 16:23 UTC, ShivanshVij commented on protoc-gen-frpc/templates/client.templ
>                      err := q.Push(res)
Do the unlock before you push

2022-06-14 16:27 UTC, ShivanshVij commented
```go
func (x *Request) decode(d *packet.Decoder) error {
	if d.Nil() {
		return nil
	}
	var err error

	x.error, err = d.Error()
	if err != nil {
		x.flags, err = d.Uint8()
		if err != nil {
			return err
		}

		x.Message, err = d.String()
		if err != nil {
			return err
		}
	} else {
		x.flags, err = d.Uint8()
		if err != nil {
			return err
		}
	}
	return nil
}
```

2022-06-14 18:34 UTC, ShivanshVij commented
Full echo hacked example:
```go
// Code generated by FRPC v0.5.1, DO NOT EDIT.
// source: protoc-gen-frpc/examples/echo/echo.proto

package echo

import (
	"fmt"
	"github.com/loopholelabs/frisbee/pkg/packet"
	"errors"
	"go.uber.org/atomic"
	"io"

	"github.com/loopholelabs/frisbee"
	"github.com/rs/zerolog"
	"crypto/tls"
	"context"

	"sync"
	"github.com/loopholelabs/common/pkg/queue"
)

const CloseFlag uint8 = 0x1
const ErrorFlag uint8 = 0x2

func AddClose(flags uint8) uint8 {
	return flags | CloseFlag
}

func CheckClose(flags uint8) bool {
	return flags & CloseFlag == 1
}

const streamIdLength = 24
const statusLength = 8
const streamStatusMask uint32 = 0xFF000000

var (
	NilDecode = errors.New("cannot decode into a nil root struct")
)

type Request struct {
	error error
	flags uint8

	Message string
}

func NewRequest() *Request {
	return &Request{}
}

func (x *Request) Error(p *packet.Packet, err error) {
	packet.Encoder(p).Error(err)
}

func (x *Request) Encode(p *packet.Packet) {
	if x == nil {
		packet.Encoder(p).Nil()
	} else if x.error != nil {
		packet.Encoder(p).Error(x.error).Uint8(x.flags)
	} else {
		packet.Encoder(p).Uint8(x.flags).String(x.Message)
	}
}

func (x *Request) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := packet.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Request) decode(d *packet.Decoder) error {
	if d.Nil() {
		return nil
	}
	var err error

	x.error, err = d.Error()
	if err != nil {
		x.flags, err = d.Uint8()
		if err != nil {
			return err
		}

		x.Message, err = d.String()
		if err != nil {
			return err
		}
	} else {
		x.flags, err = d.Uint8()
		if err != nil {
			return err
		}
	}
	return nil
}

type Response struct {
	error error
	flags uint8

	Message string
}

func NewResponse() *Response {
	return &Response{}
}

func (x *Response) Error(p *packet.Packet, err error) {
	packet.Encoder(p).Error(err)
}

func (x *Response) Encode(p *packet.Packet) {
	if x == nil {
		packet.Encoder(p).Nil()
	} else if x.error != nil {
		packet.Encoder(p).Error(x.error).Uint8(x.flags)
	} else {
		packet.Encoder(p).Uint8(x.flags).String(x.Message)
	}
}

func (x *Response) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := packet.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Response) decode(d *packet.Decoder) error {
	if d.Nil() {
		return nil
	}
	var err error
	var flags uint8

	x.error, err = d.Error()
	if err != nil {
		flags, err = d.Uint8()
		if err != nil {
			return err
		}
		x.flags = flags

		x.Message, err = d.String()
		if err != nil {
			return err
		}
	}
	return nil
}

type EchoService interface {
	Echo(context.Context, *Request) (*Response, error)

	EchoStream(srv *EchoStreamServer) error
}

type Server struct {
	*frisbee.Server

	nextEchoStream       uint16
	nextEchoStreamMu     sync.RWMutex
	inflightEchoStream   map[uint16]*EchoStreamServer
	inflightEchoStreamMu sync.RWMutex
	streams map[*frisbee.Async]map[uint16]*EchoStreamServer
}

func NewServer(echoService EchoService, tlsConfig *tls.Config, logger *zerolog.Logger) (*Server, error) {
	var s *Server
	table := make(frisbee.HandlerTable)

	table[10] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		req := NewRequest()
		err := req.Decode(incoming.Content.B)
		if err == nil {
			var res *Response
			outgoing = incoming
			outgoing.Content.Reset()
			res, err = echoService.Echo(ctx, req)
			if err != nil {
				res.Error(outgoing, err)
			} else {
				res.Encode(outgoing)
			}
			outgoing.Metadata.ContentLength = uint32(len(outgoing.Content.B))
		}
		return
	}

	table[11] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		req := NewRequest()
		err := req.Decode(incoming.Content.B)
		if err == nil {
			var srv *EchoStreamServer
			var ok bool
			s.inflightEchoStreamMu.Lock()
			if srv, ok = s.inflightEchoStream[incoming.Metadata.Id]; ok {
				s.inflightEchoStreamMu.Unlock()
				srv.receivedPackets.Push(req)
			} else {
				srv = &EchoStreamServer{
					context: ctx,
					receivedPackets: queue.NewCircular[Request, *Request](100),
					closed: atomic.NewBool(false),
				}
				s.inflightEchoStream[incoming.Metadata.Id] = srv
				s.inflightEchoStreamMu.Unlock()
				srv.receivedPackets.Push(req)
				id := incoming.Metadata.Id
				conn := ctx.Value("conn").(*frisbee.Async)
				if potato, ok := s.streams[conn]; ok {
					potato[srv] = struct{}{}
				} else {
					s.streams[conn] = make(map[*EchoStreamServer]struct{})
				}
				srv.recv = func() (*Request, error) {
					if srv.closed.Load() {
						srv.staleMu.Lock()
						if len(srv.stalePackets) > 0 {
							var r *Request
							r, srv.stalePackets = srv.stalePackets[0], srv.stalePackets[1:]
							srv.staleMu.Unlock()
							return r, nil
						}
						srv.staleMu.Unlock()
						return nil, io.EOF
					}

					if conn.Closed() {
						srv.close()
					}

					readPacket, err := srv.receivedPackets.Pop()
					if err != nil {
						if srv.closed.Load() {
							srv.staleMu.Lock()
							if len(srv.stalePackets) > 0 {
								var r *Request
								r, srv.stalePackets = srv.stalePackets[0], srv.stalePackets[1:]
								srv.staleMu.Unlock()
								return r, nil
							}
							srv.staleMu.Unlock()
						}
						return nil, io.EOF
					}

					return readPacket, nil
				}
				srv.send = func(m *Response) error {
					if srv.closed.Load() {
						p := packet.Get()
						p.Metadata.Operation = 11

						p.Metadata.Id = id

						m.Encode(p)
						p.Metadata.ContentLength = uint32(len(p.Content.B))
						err := conn.WritePacket(p)
						if err != nil {
							packet.Put(p)
							return err
						}
						packet.Put(p)
						return nil
					}
					return fmt.Errorf("closed af")
				}

				go func() {

					err := echoService.EchoStream(srv)

					if err != nil {
						res := Response{error: err}
						res.flags = res.flags & ErrorFlag
						srv.CloseAndSend(&res)
					} else {
						res := Response{}
						srv.CloseAndSend(&res)
					}
					s.inflightEchoStreamMu.Lock()
					delete(s.inflightEchoStream, incoming.Metadata.Id)
					s.inflightEchoStreamMu.Unlock()
				}()

			}
		}
		return
	}
	var fsrv *frisbee.Server
	var err error
	if tlsConfig != nil {
		fsrv, err = frisbee.NewServer(table, frisbee.WithTLS(tlsConfig), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	} else {
		fsrv, err = frisbee.NewServer(table, frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	}

	fsrv.ConnContext = func(ctx context.Context, conn *frisbee.Async) context.Context {
		return context.WithValue(ctx, "conn", conn)
	}
	s, err = &Server{
		Server: fsrv,
	}, nil

	fsrv.SetOnClosed(func(async *frisbee.Async, err error) {
		// lock
		if livingStreams, ok := s.streams[async]; ok {
			// unlock
			for streamID, stream := range livingStreams {
				// Log: killing stream %d (streamID)
				stream.close()
			}
		}
	})

	s.nextEchoStream = 0
	s.inflightEchoStream = make(map[uint16]*EchoStreamServer)
	return s, err
}

type EchoStreamServer struct {
	context context.Context
	recv    func() (*Request, error)
	send    func(*Response) error
	receivedPackets   *queue.Circular[Request, *Request]
	stalePackets []*Request
	staleMu sync.Mutex
	closed *atomic.Bool
}

func (x *EchoStreamServer) Context() context.Context {
	return x.context
}

func (x *EchoStreamServer) Recv() (*Request, error) {
	return x.recv()
}
func (x *EchoStreamServer) Send(m *Response) error {
	return x.send(m)
}

func (x *EchoStreamServer) close() {
	x.staleMu.Lock()
	x.closed.Store(true)
	x.stalePackets = x.receivedPackets.Drain()
	x.staleMu.Unlock()
	x.receivedPackets.Close()
}

func (x *EchoStreamServer) CloseAndSend(m *Response) error {
	m.flags = m.flags | CloseFlag
	defer x.close()
	return x.send(m)
}

type Client struct {
	*frisbee.Client
	nextEcho             uint16
	nextEchoMu           sync.RWMutex
	inflightEchoMu       sync.RWMutex
	inflightEcho         map[uint16]chan *R [...]

2022-07-19 17:29 UTC, ShivanshVij commented
@SuperManifolds There are definitely more than a couple bugs still remaining in this PR:

1. The `*Count` type is used in the generated code, but the actual variable isn't declared. I've attempted to fix this in [the latest commit](https://github.com/loopholelabs/frisbee/pull/128/commits/73ca39b280aa8b3d44dbc49b670e78fdb80e47b2) but I'm not sure if that was correct

2. The Generated code isn't properly using polyglot, if you use the updated `echo.proto` file I've created in the [latest commit](https://github.com/loopholelabs/frisbee/pull/128/commits/73ca39b280aa8b3d44dbc49b670e78fdb80e47b2), you'll see that the generated code uses the variable `p` for encoding, but `p` does not exist. Not sure what's going on there.

2022-07-19 17:29 UTC, ShivanshVij requested changes
@SuperManifolds There are definitely more than a couple bugs still remaining in this PR:

1. The `*Count` type is used in the generated code, but the actual variable isn't declared. I've attempted to fix this in [the latest commit](https://github.com/loopholelabs/frisbee/pull/128/commits/73ca39b280aa8b3d44dbc49b670e78fdb80e47b2) but I'm not sure if that was correct

2. The Generated code isn't properly using polyglot, if you use the updated `echo.proto` file I've created in the [latest commit](https://github.com/loopholelabs/frisbee/pull/128/commits/73ca39b280aa8b3d44dbc49b670e78fdb80e47b2), you'll see that the generated code uses the variable `p` for encoding, but `p` does not exist. Not sure what's going on there.

2022-07-21 03:43 UTC, ShivanshVij commented
Because we've moved all of fRPC over to https://github.com/loopholelabs/frpc-go, I'm closing this PR after copying all of it over to the `streaming` branch of the new repo

2022-07-21 03:43 UTC, closed without merging